import type { Question } from './types';

// Scoring function helper: linear scale from min to max -> 0-10
const linearScale = (value: number, min: number, max: number, reverse: boolean = false) => {
  const score = ((value - min) / (max - min)) * 10;
  return reverse ? 10 - score : score;
};

// MCQ score maps directly to the value. We use a 0-10 scale for consistency.
const mcqScore = (value: number) => value;

export const questions: Question[] = [
  // A. METABOLIC & BLOOD SUGAR LOAD
  {
    id: 'q1',
    pillar: 'metabolic',
    text: 'How often do you consume sugary drinks (soda, sweetened juice, energy drinks)?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'Never or rarely' },
      { value: 2, label: 'A few times a month' },
      { value: 6, label: 'A few times a week' },
      { value: 10, label: 'Daily or more' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q2',
    pillar: 'metabolic',
    text: 'How frequently do you eat ultra-processed foods (fast food, packaged snacks)?',
    type: 'multiple-choice',
    options: [
      { value: 1, label: 'Rarely' },
      { value: 4, label: 'Sometimes' },
      { value: 8, label: 'Often' },
      { value: 10, label: 'Very frequently' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q3',
    pillar: 'metabolic',
    text: 'Do you experience energy crashes or sudden fatigue after meals?',
    type: 'multiple-choice',
    options: [
      { value: 1, label: 'Never' },
      { value: 4, label: 'Sometimes' },
      { value: 8, label: 'Often' },
      { value: 10, label: 'Almost always' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q4',
    pillar: 'metabolic',
    text: 'How consistent are your meal times each day?',
    type: 'slider',
    min: 0,
    max: 10,
    step: 1,
    minLabel: 'Very inconsistent',
    maxLabel: 'Very consistent',
    scoringFunction: (value) => linearScale(value, 0, 10, true), // Reverse scored
  },
  {
    id: 'q5',
    pillar: 'metabolic',
    text: 'How often do you snack late at night?',
    type: 'multiple-choice',
    options: [
      { value: 1, label: 'Rarely or never' },
      { value: 4, label: '1-2 nights a week' },
      { value: 7, label: '3-4 nights a week' },
      { value: 10, label: 'Most nights' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q6',
    pillar: 'metabolic',
    text: 'How many hours per day are you physically inactive (sitting, lying down)?',
    type: 'slider',
    min: 0,
    max: 16,
    step: 1,
    minLabel: 'Very few',
    maxLabel: 'Many hours',
    scoringFunction: (value) => linearScale(value, 0, 16),
  },
  {
    id: 'q7',
    pillar: 'metabolic',
    text: 'How often do you feel hungry shortly after eating a full meal?',
    type: 'multiple-choice',
    options: [
      { value: 1, label: 'Rarely' },
      { value: 4, label: 'Sometimes' },
      { value: 7, label: 'Often' },
      { value: 10, label: 'Almost always' },
    ],
    scoringFunction: mcqScore,
  },

  // B. INFLAMMATION & CANCER-LINKED LIFESTYLE SIGNALS
  {
    id: 'q8',
    pillar: 'inflammatory',
    text: 'How often do you smoke or vape (including social use)?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'Never' },
      { value: 5, label: 'Rarely' },
      { value: 8, label: 'Socially/Weekly' },
      { value: 10, label: 'Daily' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q9',
    pillar: 'inflammatory',
    text: 'How frequently do you consume alcohol?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'Never or rarely' },
      { value: 3, label: '1-3 drinks a week' },
      { value: 7, label: '4-7 drinks a week' },
      { value: 10, label: 'More than 7 drinks a week' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q10',
    pillar: 'inflammatory',
    text: 'How often do you eat red or processed meats?',
    type: 'multiple-choice',
    options: [
      { value: 1, label: 'Rarely or never' },
      { value: 4, label: 'A few times a week' },
      { value: 8, label: 'Most days' },
      { value: 10, label: 'Daily' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q11',
    pillar: 'inflammatory',
    text: 'How often do you include fruits, vegetables, or fiber-rich foods in meals?',
    type: 'slider',
    min: 0,
    max: 10,
    step: 1,
    minLabel: 'Rarely',
    maxLabel: 'Every meal',
    scoringFunction: (value) => linearScale(value, 0, 10, true), // Reverse scored
  },
  {
    id: 'q12',
    pillar: 'inflammatory',
    text: 'How consistent is your sleep schedule?',
    type: 'slider',
    min: 0,
    max: 10,
    step: 1,
    minLabel: 'Very inconsistent',
    maxLabel: 'Very consistent',
    scoringFunction: (value) => linearScale(value, 0, 10, true), // Reverse scored
  },
  {
    id: 'q13',
    pillar: 'inflammatory',
    text: 'How often do you feel chronically stressed or tense?',
    type: 'multiple-choice',
    options: [
      { value: 1, label: 'Rarely' },
      { value: 4, label: 'Sometimes' },
      { value: 8, label: 'Often' },
      { value: 10, label: 'Constantly' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q14',
    pillar: 'inflammatory',
    text: 'How often do you feel physically run-down without a clear reason?',
    type: 'multiple-choice',
    options: [
      { value: 1, label: 'Rarely' },
      { value: 4, label: 'Sometimes' },
      { value: 8, label: 'Often' },
      { value: 10, label: 'Most of the time' },
    ],
    scoringFunction: mcqScore,
  },

  // C. CARDIOVASCULAR STRAIN
  {
    id: 'q15',
    pillar: 'cardiovascular',
    text: 'How often do you engage in moderate physical activity (brisk walking, cycling, gym)?',
    type: 'multiple-choice',
    options: [
      { value: 10, label: 'Rarely or never' },
      { value: 7, label: '1-2 times a week' },
      { value: 3, label: '3-4 times a week' },
      { value: 0, label: '5+ times a week' },
    ],
    scoringFunction: mcqScore, // Already reversed in options
  },
  {
    id: 'q16',
    pillar: 'cardiovascular',
    text: 'Do you experience shortness of breath during mild activity?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'Never' },
      { value: 5, label: 'Sometimes' },
      { value: 10, label: 'Frequently' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q17',
    pillar: 'cardiovascular',
    text: 'How often do you feel unexplained chest tightness or discomfort?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'Never' },
      { value: 5, label: 'Rarely' },
      { value: 10, label: 'Sometimes or often' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q18',
    pillar: 'cardiovascular',
    text: 'How frequently do you consume high-salt or heavily seasoned foods?',
    type: 'multiple-choice',
    options: [
      { value: 1, label: 'Rarely' },
      { value: 4, label: 'Sometimes' },
      { value: 8, label: 'Often' },
      { value: 10, label: 'Almost every meal' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q19',
    pillar: 'cardiovascular',
    text: 'How often do you feel physically exhausted despite adequate sleep?',
    type: 'multiple-choice',
    options: [
      { value: 1, label: 'Rarely' },
      { value: 4, label: 'Sometimes' },
      { value: 8, label: 'Often' },
      { value: 10, label: 'Almost always' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q20',
    pillar: 'cardiovascular',
    text: 'How aware are you of your family’s general health history?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'Very aware, no major concerns' },
      { value: 2, label: 'Aware, some family history of issues' },
      { value: 4, label: 'Not very aware' },
    ],
    scoringFunction: mcqScore,
  },

  // D. HORMONAL & STRESS LOAD
  {
    id: 'q21',
    pillar: 'hormonal',
    text: 'How would you rate your overall sleep quality?',
    type: 'slider',
    min: 0,
    max: 10,
    step: 1,
    minLabel: 'Very poor',
    maxLabel: 'Excellent',
    scoringFunction: (value) => linearScale(value, 0, 10, true), // Reverse scored
  },
  {
    id: 'q22',
    pillar: 'hormonal',
    text: 'How often do you rely on caffeine to get through the day?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'Never' },
      { value: 4, label: 'Sometimes' },
      { value: 7, label: 'Most days' },
      { value: 10, label: 'Multiple times a day' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q23',
    pillar: 'hormonal',
    text: 'How often do you feel anxious, restless, or unable to relax?',
    type: 'multiple-choice',
    options: [
      { value: 1, label: 'Rarely' },
      { value: 4, label: 'Sometimes' },
      { value: 8, label: 'Often' },
      { value: 10, label: 'Constantly' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q24',
    pillar: 'hormonal',
    text: 'How frequently do you use screens (phone, laptop) late at night?',
    type: 'slider',
    min: 0,
    max: 10,
    step: 1,
    minLabel: 'Never',
    maxLabel: 'Every night',
    scoringFunction: (value) => linearScale(value, 0, 10),
  },
  {
    id: 'q25',
    pillar: 'hormonal',
    text: 'How often do you wake up feeling unrefreshed?',
    type: 'multiple-choice',
    options: [
      { value: 1, label: 'Rarely' },
      { value: 4, label: 'Sometimes' },
      { value: 8, label: 'Often' },
      { value: 10, label: 'Almost always' },
    ],
    scoringFunction: mcqScore,
  },

  // E. LIFESTYLE STABILITY & RECOVERY
  {
    id: 'q26',
    pillar: 'stability',
    text: 'How predictable is your daily routine?',
    type: 'slider',
    min: 0,
    max: 10,
    step: 1,
    minLabel: 'Chaotic',
    maxLabel: 'Very predictable',
    scoringFunction: (value) => linearScale(value, 0, 10, true),
  },
  {
    id: 'q27',
    pillar: 'stability',
    text: 'How often do financial concerns cause stress or worry?',
    type: 'multiple-choice',
    options: [
      { value: 1, label: 'Rarely' },
      { value: 4, label: 'Sometimes' },
      { value: 8, label: 'Often' },
      { value: 10, label: 'Constantly' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q28',
    pillar: 'stability',
    text: 'How often do you feel overwhelmed by responsibilities?',
    type: 'multiple-choice',
    options: [
      { value: 1, label: 'Rarely' },
      { value: 4, label: 'Sometimes' },
      { value: 8, label: 'Often' },
      { value: 10, label: 'Constantly' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q29',
    pillar: 'stability',
    text: 'How much time do you regularly dedicate to rest or personal recovery?',
    type: 'slider',
    min: 0,
    max: 10,
    step: 1,
    minLabel: 'Very little',
    maxLabel: 'Ample time',
    scoringFunction: (value) => linearScale(value, 0, 10, true), // Reverse scored
  },
  {
    id: 'q30',
    pillar: 'stability',
    text: 'How supported do you feel by people around you?',
    type: 'slider',
    min: 0,
    max: 10,
    step: 1,
    minLabel: 'Not at all',
    maxLabel: 'Very supported',
    scoringFunction: (value) => linearScale(value, 0, 10, true), // Reverse scored
  },
  {
    id: 'q31',
    pillar: 'stability',
    text: 'How often do you suppress emotions instead of addressing them?',
    type: 'slider',
    min: 0,
    max: 10,
    step: 1,
    minLabel: 'Never',
    maxLabel: 'Always',
    scoringFunction: (value) => linearScale(value, 0, 10),
  },
  {
    id: 'q32',
    pillar: 'stability',
    text: 'How often do you feel "on edge" without knowing why?',
    type: 'multiple-choice',
    options: [
      { value: 1, label: 'Rarely' },
      { value: 4, label: 'Sometimes' },
      { value: 8, label: 'Often' },
      { value: 10, label: 'Constantly' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q33',
    pillar: 'stability',
    text: 'How frequently do you feel mentally overloaded or burned out?',
    type: 'multiple-choice',
    options: [
      { value: 1, label: 'Rarely' },
      { value: 4, label: 'Sometimes' },
      { value: 8, label: 'Often' },
      { value: 10, label: 'Constantly' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q34',
    pillar: 'stability',
    text: 'How often do you feel your lifestyle is unsustainable long-term?',
    type: 'slider',
    min: 0,
    max: 10,
    step: 1,
    minLabel: 'Never',
    maxLabel: 'Very often',
    scoringFunction: (value) => linearScale(value, 0, 10),
  },
  {
    id: 'q35',
    pillar: 'stability',
    text: 'How confident are you that your current habits support long-term health?',
    type: 'slider',
    min: 0,
    max: 10,
    step: 1,
    minLabel: 'Not confident',
    maxLabel: 'Very confident',
    scoringFunction: (value) => linearScale(value, 0, 10, true), // Reverse scored
  },
];
