import type { Question, PillarId } from './types';

// Scoring is now based on the value of the selected option.
// The scoring function is a simple pass-through.
const getScore = (value: number) => value;

export const questions: Question[] = [
  // 1. Diet & Nutrition
  {
    id: 'q1',
    pillar: 'diet',
    text: 'How often do you eat fresh fruits and vegetables per day?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'Rarely' },
      { value: 1, label: '1-2 times' },
      { value: 2, label: '3+ times' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q2',
    pillar: 'diet',
    text: 'How often do you consume processed or fast food?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Rarely' },
      { value: 1, label: '1-2 times/week' },
      { value: 0, label: '3+ times/week' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q3',
    pillar: 'diet',
    text: 'Do you track your daily calorie intake?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Yes, consistently' },
      { value: 1, label: 'Sometimes' },
      { value: 0, label: 'No' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q4',
    pillar: 'diet',
    text: 'How often do you drink sugary beverages?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Never' },
      { value: 1, label: 'Sometimes' },
      { value: 0, label: 'Often' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q5',
    pillar: 'diet',
    text: 'How much water do you drink daily?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: '2+ liters' },
      { value: 1, label: '1-2 liters' },
      { value: 0, label: '<1 liter' },
    ],
    scoringFunction: getScore,
  },
  // 2. Physical Activity
  {
    id: 'q6',
    pillar: 'activity',
    text: 'How many days per week do you engage in moderate exercise (30+ min)?',
    type: 'multiple-choice',
    options: [
        { value: 2, label: '5-7 days' },
        { value: 1, label: '2-4 days' },
        { value: 0, label: '0-1 days' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q7',
    pillar: 'activity',
    text: 'How often do you perform strength/resistance training?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: '2+ times/week' },
      { value: 1, label: '1-2 times/week' },
      { value: 0, label: 'Never' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q8',
    pillar: 'activity',
    text: 'Do you have a mostly sedentary job or lifestyle?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'No' },
      { value: 1, label: 'Somewhat' },
      { value: 0, label: 'Yes' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q9',
    pillar: 'activity',
    text: 'How often do you walk or cycle instead of using motorized transport?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Often' },
      { value: 1, label: 'Sometimes' },
      { value: 0, label: 'Rarely' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q10',
    pillar: 'activity',
    text: 'How often do you stretch or do flexibility exercises?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Regularly' },
      { value: 1, label: 'Sometimes' },
      { value: 0, label: 'Never' },
    ],
    scoringFunction: getScore,
  },
  // 3. Sleep & Recovery
  {
    id: 'q11',
    pillar: 'sleep',
    text: 'On average, how many hours of sleep do you get per night?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: '7-9 hours' },
      { value: 1, label: '6-7 hours' },
      { value: 0, label: '<6 hours' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q12',
    pillar: 'sleep',
    text: 'How often do you have trouble falling asleep or staying asleep?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Rarely' },
      { value: 1, label: 'Sometimes' },
      { value: 0, label: 'Often' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q13',
    pillar: 'sleep',
    text: 'Do you feel rested when you wake up?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Almost always' },
      { value: 1, label: 'Sometimes' },
      { value: 0, label: 'Rarely' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q14',
    pillar: 'sleep',
    text: 'How often do you take naps during the day?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Rarely' },
      { value: 1, label: 'Sometimes' },
      { value: 0, label: 'Often' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q15',
    pillar: 'sleep',
    text: 'Do you have a consistent sleep schedule?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Yes' },
      { value: 1, label: 'Somewhat' },
      { value: 0, label: 'No' },
    ],
    scoringFunction: getScore,
  },
  // 4. Stress & Mental Health
  {
    id: 'q16',
    pillar: 'stress',
    text: 'How often do you feel stressed during a typical week?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Rarely' },
      { value: 1, label: 'Sometimes' },
      { value: 0, label: 'Often' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q17',
    pillar: 'stress',
    text: 'Do you practice relaxation or mindfulness techniques regularly?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Yes' },
      { value: 1, label: 'Sometimes' },
      { value: 0, label: 'No' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q18',
    pillar: 'stress',
    text: 'How often do you feel anxious or overwhelmed?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Rarely' },
      { value: 1, label: 'Sometimes' },
      { value: 0, label: 'Constantly' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q19',
    pillar: 'stress',
    text: 'Do you feel you have a good work-life balance?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Yes' },
      { value: 1, label: 'It varies' },
      { value: 0, label: 'No' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q20',
    pillar: 'stress',
    text: 'How often do you feel burnout or fatigue?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Rarely' },
      { value: 1, label: 'Sometimes' },
      { value: 0, label: 'Often' },
    ],
    scoringFunction: getScore,
  },
  // 5. Substance Use
  {
    id: 'q21',
    pillar: 'habits',
    text: 'Do you smoke or use tobacco products?',
    type: 'multiple-choice',
    options: [
      { value: 3, label: 'No' },
      { value: 1, label: 'Occasionally' },
      { value: 0, label: 'Yes' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q22',
    pillar: 'habits',
    text: 'How often do you consume alcohol per week?',
    type: 'multiple-choice',
    options: [
      { value: 3, label: '<3 drinks' },
      { value: 1, label: '3-7 drinks' },
      { value: 0, label: '>7 drinks' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q23',
    pillar: 'habits',
    text: 'Do you use recreational drugs or stimulants?',
    type: 'multiple-choice',
    options: [
      { value: 3, label: 'Never' },
      { value: 1, label: 'Rarely' },
      { value: 0, label: 'Sometimes/Often' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q24',
    pillar: 'habits',
    text: 'How often do you consume caffeine daily?',
    type: 'multiple-choice',
    options: [
      { value: 3, label: 'None' },
      { value: 1, label: '1-2 cups' },
      { value: 0, label: '3+ cups' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q25',
    pillar: 'habits',
    text: 'Do you take prescription medications for long-term conditions?',
    type: 'multiple-choice',
    options: [
      { value: 3, label: 'No' },
      { value: 1, label: 'Yes, 1-2' },
      { value: 0, label: 'Yes, 3+' },
    ],
    scoringFunction: getScore,
  },
  // 6. Medical & Family History
  {
    id: 'q26',
    pillar: 'medical',
    text: 'Do you have a family history of diabetes, heart disease, or cancer?',
    type: 'multiple-choice',
    options: [
      { value: 3, label: 'No' },
      { value: 2, label: 'Minor Risk' },
      { value: 0, label: 'Major Risk' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q27',
    pillar: 'medical',
    text: 'Do you have any diagnosed chronic health conditions?',
    type: 'multiple-choice',
    options: [
      { value: 3, label: 'No' },
      { value: 0, label: 'Yes' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q28',
    pillar: 'medical',
    text: 'How often do you get medical check-ups?',
    type: 'multiple-choice',
    options: [
      { value: 3, label: 'Annually' },
      { value: 1, label: 'Every few years' },
      { value: 0, label: 'Rarely/Never' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q29',
    pillar: 'medical',
    text: 'Do you monitor your blood pressure, blood sugar, or cholesterol?',
    type: 'multiple-choice',
    options: [
      { value: 3, label: 'Yes, regularly' },
      { value: 1, label: 'Sometimes' },
      { value: 0, label: 'No' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q30',
    pillar: 'medical',
    text: 'Have you had significant unexplained weight change recently?',
    type: 'multiple-choice',
    options: [
      { value: 3, label: 'No' },
      { value: 0, label: 'Yes' },
    ],
    scoringFunction: getScore,
  },
  // 7. Lifestyle & Habits
  {
    id: 'q31',
    pillar: 'lifestyle',
    text: 'How often do you feel energetic during the day?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Almost always' },
      { value: 1, label: 'Sometimes' },
      { value: 0, label: 'Rarely' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q32',
    pillar: 'lifestyle',
    text: 'Do you take steps to reduce sedentary behavior at home/work?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Yes' },
      { value: 1, label: 'Sometimes' },
      { value: 0, label: 'No' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q33',
    pillar: 'lifestyle',
    text: 'How often do you engage in hobbies or leisure activities?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Often' },
      { value: 1, label: 'Sometimes' },
      { value: 0, label: 'Rarely' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q34',
    pillar: 'lifestyle',
    text: 'Do you feel socially connected and supported?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Yes' },
      { value: 1, label: 'Somewhat' },
      { value: 0, label: 'No' },
    ],
    scoringFunction: getScore,
  },
  {
    id: 'q35',
    pillar: 'lifestyle',
    text: 'How often do you feel you make healthy lifestyle choices consistently?',
    type: 'multiple-choice',
    options: [
      { value: 2, label: 'Consistently' },
      { value: 1, label: 'Often' },
      { value: 0, label: 'Rarely' },
    ],
    scoringFunction: getScore,
  },
];
