import type { Question } from './types';

// Scoring function helper: linear scale from min to max -> 0-10
const linearScale = (value: number, min: number, max: number, reverse: boolean = false) => {
  const score = ((value - min) / (max - min)) * 10;
  return reverse ? 10 - score : score;
};

// MCQ score maps directly to the value. We use a 0-10 scale for consistency.
const mcqScore = (value: number) => value;

export const questions: Question[] = [
  // 1. Diet & Nutrition
  {
    id: 'q1',
    pillar: 'diet',
    text: 'How often do you eat fresh fruits and vegetables per day?',
    type: 'multiple-choice',
    options: [
      { value: 10, label: 'Never' },
      { value: 7, label: '1-2 times' },
      { value: 3, label: '3-4 times' },
      { value: 0, label: '5+ times' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q2',
    pillar: 'diet',
    text: 'How often do you consume processed or fast food?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'Rarely' },
      { value: 3, label: '1-2 times/week' },
      { value: 7, label: '3-4 times/week' },
      { value: 10, label: 'Daily' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q3',
    pillar: 'diet',
    text: 'Do you track your daily calorie intake?',
    type: 'multiple-choice',
    options: [
      { value: 10, label: 'No' },
      { value: 5, label: 'Sometimes' },
      { value: 0, label: 'Yes, consistently' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q4',
    pillar: 'diet',
    text: 'How often do you drink sugary beverages?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'Never' },
      { value: 3, label: 'Rarely' },
      { value: 7, label: 'Sometimes' },
      { value: 10, label: 'Often' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q5',
    pillar: 'diet',
    text: 'How much water do you drink daily (liters)?',
    type: 'slider',
    min: 0,
    max: 4,
    step: 0.5,
    minLabel: '0L',
    maxLabel: '4L+',
    scoringFunction: (value) => linearScale(value, 0, 4, true),
  },
  // 2. Physical Activity
  {
    id: 'q6',
    pillar: 'activity',
    text: 'How many days per week do you engage in moderate exercise (30+ min)?',
    type: 'slider',
    min: 0,
    max: 7,
    step: 1,
    minLabel: '0 days',
    maxLabel: '7 days',
    scoringFunction: (value) => linearScale(value, 0, 7, true),
  },
  {
    id: 'q7',
    pillar: 'activity',
    text: 'How often do you perform strength/resistance training?',
    type: 'multiple-choice',
    options: [
      { value: 10, label: 'Never' },
      { value: 7, label: 'Rarely' },
      { value: 3, label: '1-2 times/week' },
      { value: 0, label: '3+ times/week' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q8',
    pillar: 'activity',
    text: 'Do you have a mostly sedentary job or lifestyle?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'No' },
      { value: 5, label: 'Somewhat' },
      { value: 10, label: 'Yes' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q9',
    pillar: 'activity',
    text: 'How often do you walk or cycle instead of using motorized transport?',
    type: 'multiple-choice',
    options: [
      { value: 10, label: 'Rarely' },
      { value: 7, label: 'Sometimes' },
      { value: 3, label: 'Often' },
      { value: 0, label: 'Very Often' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q10',
    pillar: 'activity',
    text: 'How often do you stretch or do flexibility exercises?',
    type: 'multiple-choice',
    options: [
      { value: 10, label: 'Never' },
      { value: 7, label: 'Rarely' },
      { value: 3, label: 'Sometimes' },
      { value: 0, label: 'Regularly' },
    ],
    scoringFunction: mcqScore,
  },
  // 3. Sleep & Recovery
  {
    id: 'q11',
    pillar: 'sleep',
    text: 'On average, how many hours of sleep do you get per night?',
    type: 'slider',
    min: 0,
    max: 12,
    step: 1,
    minLabel: '0-4 hours',
    maxLabel: '8+ hours',
    scoringFunction: (value) => (value < 7 || value > 9 ? linearScale(Math.abs(value - 8), 0, 4) : 0),
  },
  {
    id: 'q12',
    pillar: 'sleep',
    text: 'How often do you have trouble falling asleep or staying asleep?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'Rarely' },
      { value: 4, label: 'Sometimes' },
      { value: 8, label: 'Often' },
      { value: 10, label: 'Almost always' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q13',
    pillar: 'sleep',
    text: 'Do you feel rested when you wake up?',
    type: 'multiple-choice',
    options: [
      { value: 10, label: 'Rarely' },
      { value: 7, label: 'Sometimes' },
      { value: 3, label: 'Often' },
      { value: 0, label: 'Almost always' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q14',
    pillar: 'sleep',
    text: 'How often do you take naps during the day?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'Rarely' },
      { value: 5, label: 'Sometimes' },
      { value: 8, label: 'Often' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q15',
    pillar: 'sleep',
    text: 'Do you have a consistent sleep schedule?',
    type: 'multiple-choice',
    options: [
      { value: 10, label: 'No' },
      { value: 5, label: 'Somewhat' },
      { value: 0, label: 'Yes' },
    ],
    scoringFunction: mcqScore,
  },
  // 4. Stress & Mental Health
  {
    id: 'q16',
    pillar: 'stress',
    text: 'How often do you feel stressed during a typical week?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'Rarely' },
      { value: 4, label: 'Sometimes' },
      { value: 8, label: 'Often' },
      { value: 10, label: 'Constantly' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q17',
    pillar: 'stress',
    text: 'Do you practice relaxation or mindfulness techniques regularly?',
    type: 'multiple-choice',
    options: [
      { value: 10, label: 'No' },
      { value: 5, label: 'Sometimes' },
      { value: 0, label: 'Yes' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q18',
    pillar: 'stress',
    text: 'How often do you feel anxious or overwhelmed?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'Rarely' },
      { value: 4, label: 'Sometimes' },
      { value: 8, label: 'Often' },
      { value: 10, label: 'Constantly' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q19',
    pillar: 'stress',
    text: 'Do you feel you have a good work-life balance?',
    type: 'multiple-choice',
    options: [
      { value: 10, label: 'No' },
      { value: 5, label: 'It varies' },
      { value: 0, label: 'Yes' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q20',
    pillar: 'stress',
    text: 'How often do you feel burnout or fatigue?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'Rarely' },
      { value: 4, label: 'Sometimes' },
      { value: 8, label: 'Often' },
      { value: 10, label: 'Constantly' },
    ],
    scoringFunction: mcqScore,
  },
  // 5. Substance Use & 7. Lifestyle & Habits (Combined into one pillar)
  {
    id: 'q21',
    pillar: 'habits',
    text: 'Do you smoke or use tobacco products?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'No' },
      { value: 10, label: 'Yes' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q22',
    pillar: 'habits',
    text: 'How often do you consume alcohol per week?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: '0 drinks' },
      { value: 3, label: '1-3 drinks' },
      { value: 7, label: '4-7 drinks' },
      { value: 10, label: '7+ drinks' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q23',
    pillar: 'habits',
    text: 'Do you use recreational drugs or stimulants?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'Never' },
      { value: 5, label: 'Rarely' },
      { value: 10, label: 'Sometimes/Often' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q24',
    pillar: 'habits',
    text: 'How often do you consume caffeine daily?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'None' },
      { value: 2, label: '1-2 cups' },
      { value: 5, label: '3-4 cups' },
      { value: 8, label: '5+ cups' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q25',
    pillar: 'habits',
    text: 'Do you take prescription medications for long-term conditions?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'No' },
      { value: 3, label: 'Yes, 1-2' },
      { value: 7, label: 'Yes, 3+' },
    ],
    scoringFunction: mcqScore,
  },
  // 6. Medical & Family History
  {
    id: 'q26',
    pillar: 'habits',
    text: 'Do you have a family history of diabetes, heart disease, or cancer?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'No' },
      { value: 5, label: 'Unsure' },
      { value: 8, label: 'Yes' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q27',
    pillar: 'habits',
    text: 'Do you have any diagnosed chronic health conditions?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'No' },
      { value: 8, label: 'Yes' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q28',
    pillar: 'habits',
    text: 'How often do you get medical check-ups?',
    type: 'multiple-choice',
    options: [
      { value: 10, label: 'Rarely/Never' },
      { value: 5, label: 'Every few years' },
      { value: 0, label: 'Annually' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q29',
    pillar: 'habits',
    text: 'Do you monitor your blood pressure, blood sugar, or cholesterol?',
    type: 'multiple-choice',
    options: [
      { value: 10, label: 'No' },
      { value: 5, label: 'Sometimes' },
      { value: 0, label: 'Yes, regularly' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q30',
    pillar: 'habits',
    text: 'Have you had significant unexplained weight change recently?',
    type: 'multiple-choice',
    options: [
      { value: 0, label: 'No' },
      { value: 8, label: 'Yes' },
    ],
    scoringFunction: mcqScore,
  },
  // 7. Lifestyle & Habits
  {
    id: 'q31',
    pillar: 'stress',
    text: 'How often do you feel energetic during the day?',
    type: 'multiple-choice',
    options: [
      { value: 10, label: 'Rarely' },
      { value: 7, label: 'Sometimes' },
      { value: 3, label: 'Often' },
      { value: 0, label: 'Almost always' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q32',
    pillar: 'activity',
    text: 'Do you take steps to reduce sedentary behavior at home/work?',
    type: 'multiple-choice',
    options: [
      { value: 10, label: 'No' },
      { value: 5, label: 'Sometimes' },
      { value: 0, label: 'Yes' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q33',
    pillar: 'stress',
    text: 'How often do you engage in hobbies or leisure activities?',
    type: 'multiple-choice',
    options: [
      { value: 10, label: 'Rarely' },
      { value: 5, label: 'Sometimes' },
      { value: 0, label: 'Often' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q34',
    pillar: 'stress',
    text: 'Do you feel socially connected and supported?',
    type: 'multiple-choice',
    options: [
      { value: 10, label: 'No' },
      { value: 5, label: 'Somewhat' },
      { value: 0, label: 'Yes' },
    ],
    scoringFunction: mcqScore,
  },
  {
    id: 'q35',
    pillar: 'habits',
    text: 'How often do you feel you make healthy lifestyle choices consistently?',
    type: 'multiple-choice',
    options: [
      { value: 10, label: 'Rarely' },
      { value: 7, label: 'Sometimes' },
      { value: 3, label: 'Often' },
      { value: 0, label: 'Consistently' },
    ],
    scoringFunction: mcqScore,
  },
];
